export const businessModelStep = [
  {
    title: "Proposta de Valor",
    description:
      "Quais benefícios seu produto (ou serviço) entrega para seus clientes?",
    tag: "what",
    label: "O que?",
    hints: [
      "Qual produto/serviço você oferece para seu cliente?",
      "Sua proposta de valor deve ser compreensível para seu cliente e não, necessariamente, para um técnico no assunto.",
      "Qual o diferencial do seu produto/serviço?",
      "Em todos os itens do seu modelo de negócios, você deve ser sucinto, mantendo texto suficiente para compreensão, mas sem alongar muito o texto. Deve ser de visualização rápida.",
      "Por quê o cliente escolherá seu produto/serviço e não o da concorrência?",
      "Quais vantagens fidelizarão seu cliente ao seu negócio?",
      "O que fará com que seu cliente não busque outras opções ou concorrentes?",
      "Proposta de valor é o que faz o cliente viciar em seu produto/serviço e se fidelizar para sempre.",
      "Se você é um profissional de educação, por que o aluno vai preferir suas aulas ao invés de outro?",
      "O que torna seu produto/serviço tão especial?",
      "O que induz o cliente a voltar a obter/dar preferência ao seu produto/serviço?",
      "Se você é um(a) professor(a), uma boa proposta de valor seria: cursos de capacitação utilizando metodologias de aprendizagem ativa, com acompanhamento personalizado.",
      "Se você é um(a) profissional da construção civil, uma boa proposta de valor seria: execução de obras disponibilizando sistema para acompanhamento diário e transparente pelos clientes.",
      "Se você vai lançar um novo produto/software, uma boa proposta de valor seria: aplicativo que é executável em qualquer plataforma (responsivo).",
      "Sua proposta de valor deve ser compreensível para seu cliente e não, necessariamente, para um técnico no assunto.",
    ],
    name: "valueProposition",
  },
  {
    title: "Fonte de Receita",
    description:
      "Por quais maneiras o cliente pagará pelos benefícios recebidos?",
    tag: "how-much",
    label: "Quanto?",
    hints: [
      "Quais as fontes de receita? Exemplos: Venda dos produtos. Comissão. Sublocação de ambiente da empresa. Horas de consultoria.",
      "Nesse item, você também pode inserir, ao final, como o seu cliente pode pagar. Ex: Pix, Cartão, Transferência bancária. Parcelado.",
      "Você também pode vender informações (Know How). Ex: Consultoria. Acompanhamento pós-venda. Suporte.",
      "Nesse item, você deve lembrar de inserir todas as possibilidades de entrada de recursos financeiros para sua empresa.",
      "Exemplos: Vendas de produtos, Assinaturas, Aluguéis, Licenças, Leilões, Tempo de permanência (adotados em alguns restaurantes), etc.",
      "Você também pode voltar e editar itens anteriores, com base no conhecimento ou competências adquiridas durante o desenvolvimento do modelo de negócios.",
      "Em todos os itens do seu modelo de negócios, você deve ser sucinto, mantendo texto suficiente para compreensão, mas sem alongar muito o texto. Deve ser de visualização rápida.",
    ],

    name: "revenue",
  },
  {
    title: "Canais",
    description:
      "Caminhos pelos quais a empresa comunica e entrega valor para o cliente.",
    tag: "to-whom",
    label: "Para Quem?",
    hints: [
      "Seu cliente deve saber onde encontrar o seu produto/serviço.",
      "Quais serão os teus endereços? Ex: Loja física? On-line?",
      "Onde seus clientes encontram seus produtos/serviços? Ex: Instagram? Supermercado(quais)? Loja física? Feira?",
      "Você pode e deve dispor de mais de um canal.",
      "Se você comercializa moda fitness, por exemplo, você pode expor e vender seus produtos em uma academia parceira. Nesse caso, o canal é: 'academia parceira'.",
      "Você também pode voltar e editar itens anteriores, com base no conhecimento ou competências adquiridas durante o desenvolvimento do modelo de negócios.",
      "Em todos os itens do seu modelo de negócios, você deve ser sucinto, mantendo texto suficiente para compreensão, mas sem alongar muito o texto. Deve ser de visualização rápida.",
    ],

    name: "channels",
  },
  {
    title: "Relacionamento",
    description:
      "Estratégias que evitam que seus clientes corram para o concorrente.",
    tag: "to-whom",
    label: "Para Quem?",
    hints: [
      "Quais estratégias de tratamento ou acolhida aos seus clientes você utiliza? Ex: Orientações quanto ao uso de produtos ou acompanhamento pós-venda.",
      "O que você faz para que seu cliente não procure outra empresa? Ex: Cartão fidelidade, Cupons de descontos.",
      "Que tipo de atendimento personalizado você oferece aos seus clientes? Ex: Parabenizar em datas de aniversários.",
      "Disponibiliza contatos que são, de fato, acessíveis? Ex: resposta a demandas em tempo hábil.",
      "O prazer de receber um 'mimo' é explicado pela ciência (estímulos do nosso cérebro).",
      "O que você fará para reconquistar o seu cliente a cada dia? Ex.: Envio de mensagens em datas comemorativas.",
      "Ex: Envio de produtos em embalagens personalizadas.",
      "Quem ama cuida! Sua relação com o cliente precisa ser cultivada para que ele não seja conquistado por sua concorrência.",
      "Em um bom relacionamento, você deve manter seu cliente próximo. Ex.: Aniversário da loja, Envio de convites para participação em coffee breaks.",
    ],
    name: "customerRelationship",
  },
  {
    title: "Recursos Chave",
    description: "Quais os ativos fundamentais para fazer o negócio funcionar?",
    tag: "how",
    label: "Como?",
    hints: [
      "Esse item refere-se aos recursos físicos e humanos que são necessários para realizar as atividades-chave.",
      "Em todos os itens do seu modelo de negócios, você deve ser sucinto, mantendo texto suficiente para compreensão, mas sem alongar muito o texto. Deve ser de visualização rápida.",
      "Você também pode voltar e editar itens anteriores, com base no conhecimento ou competências adquiridas durante o desenvolvimento do modelo de negócios.",
      "Precisa de funcionários? Quantos?",
      "Precisa de infraestrutura de Tecnologia da Informação (TI)? Ex: Internet; Computadores, etc.",
      "Precisa de computadores?",
      "Exemplos: Energia da Operadora Local; Energia Solar; Água (principalmente se este uso é significativo).",
      "Recomenda-se, ao final, reorganizar, se for o caso, a ordem dos recursos de acordo com sua demanda ou peso na estrutura de custos.",
      "Em todos os itens do seu modelo de negócios, você deve ser sucinto, mantendo texto suficiente para compreensão, mas sem alongar muito o texto. Deve ser de visualização rápida.",
    ],

    name: "mainResources",
  },
  {
    title: "Parcerias Chave",
    description: "Quem são os seus principais fornecedores (terceirizados)?",
    tag: "how",
    label: "Como?",
    hints: [
      "Quais parcerias podem trazer benefício para tua empresa?",
      "Quais parcerias você pode firmar para beneficiar seu cliente?",
      "Exemplos: SEBRAE; Universidades (quais?), Fornecedores (quais); Banco (qual).",
      "Você possui alguma parceria que possa lhe trazer mais clientes? Como por exemplo associar sua marca a uma ONG ou projeto social que cuida de crianças carentes.",
      "Você possui parceria que possa te auxiliar em algum projeto de marketing verde? Ex.: Alguma ONG que, associada à sua marca, promova cuidado ao meio ambiente.",
      "Após visualizar de forma rápida e prática as suas atuais parcerias, você pode refletir sobre novas e então atualizar frequentemente seu modelo de negócios.",
    ],
    name: "mainPartnerships",
  },
  {
    title: "Atividades Chave",
    description: "Quais atividades mais importantes para o seu negócio?",
    tag: "how",
    label: "Como?",
    hints: [
      "Esse item deve ser descrito com uso de verbos, pois são ações. Ex: Obter e manter domínio na internet.",
      "O que você precisa fazer para ofertar sua proposta de valor?",
      "Quais atividades precisam ser realizadas para atrair seu cliente (o que descreveu em relacionamento)?",
      "O que é preciso ser feito para manter os seus canais, ou seja, o que precisa fazer para que seus produtos/serviços sejam vistos ou conhecidos pelos seus clientes, ou ainda, para que seus clientes tenham acesso aos seus produtos/serviços?",
      "O que é preciso ser feito para manter diferentes formas de pagamento para que seu cliente possa escolher como pagar?",
      "É preciso manter algum equipamento?",
      "É preciso capacitar funcionários?",
      "É preciso manter servidor internet?",
      "É preciso fazer parcerias?",
      "Ex: Elaborar e atualizar modelo de negócios.",
    ],

    name: "mainActivities",
  },
  {
    title: "Estrutura de Custos",
    description:
      "Quais os principais custos que têm peso no financeiro e são derivados da operacionalização do negócio?",
    tag: "how-much",
    label: "Quanto?",
    hints: [
      "Neste item não é preciso apontar valores, pois o modelo deve ficar exposto para todos(as) os(as) colaboradores(as). Isto será feito no Plano de Negócios.",
      "Quais seus principais custos? Exemplos: Energia; Água; Internet; Folha de pagamento; Marketing; Manutenção Equipamentos; Contratação de provedor e domínio na internet.",
      "Há investimento inicial? Quanto?",
      "Há custo com marketing? Exemplos: Site, Apps, marketing para alimentar essas estruturas virtuais.",
      "Tem custo com aluguel?",
      "Exemplo: Aquisição de matéria-prima.",
      "Quais as despesas variáveis?",
      "Quais os custos fixos?",
      "Custo com estoque? Estoque é dinheiro parado. Quanto é necessário para gerir o estoque?",
      "Quais os custos que precisam ser pagos para iniciar e/ou manter o seu negócio? Exemplos: Empréstimos não quitados; Taxa de cartão; Capacitação de colaboradores.",
      "Recomenda-se, ao final, reorganizar, se for o caso, a ordem dos custos de acordo com os maiores valores (lembrando que os valores não estão expostos). Apenas a sua ordem.",
      "Em todos os itens do seu modelo de negócios, você deve ser sucinto, mantendo texto suficiente para compreensão, mas sem alongar muito o texto. Deve ser de visualização rápida.",
      "Você também pode voltar e editar itens anteriores, com base no conhecimento ou competências adquiridas durante o desenvolvimento do modelo de negócios.",
    ],

    name: "costs",
  },
  {
    title: "Cliente",
    description: "É necessário que você defina um nicho de clientes.",
    tag: "to-whom",
    label: "Para Quem?",
    hints: [
      "Quais tipos de clientes seus produtos ou serviços atendem suas demandas? Ex.: crianças? Adolescentes? Mulheres? Homens? Estudantes? Plus size? Com necessidades especiais?",
      "Quanto mais você conhecer o perfil dos seus clientes, melhor este item será elaborado.",
      "A maioria dos seus clientes pertence a uma classe em particular: alta, média ou baixa renda? Se sim, recomendamos destacar neste campo.",
      "A maior parte dos seus clientes têm acesso à internet?",
      "Seus principais clientes adquirem seus produtos no atacado ou no varejo? (se serviço desconsidere)",
      "Quais adjetivos você atribuiria ao seu nicho de clientes? (ex: Refinados? Exigentes? Informais?) Se nenhuma característica em particular, então não incluir.",
      "Seus produtos/serviços atendem uma faixa etária em particular?",
      "Seus clientes têm um estilo de vida em específico? (Fitness? Esportivo? Com restrições alimentares?)",
      "Onde seu cliente reside? (rural? urbano?)",
      "Seus clientes, em geral, têm necessidades especiais? (ex: Cadeirantes? Dificuldade de mobilidade?)",
      "Neste item, você deve descrever o máximo possível o perfil dos seus clientes (suas principais características). Quanto mais você conhecê-los, melhor será elaborado este item e demais componentes do seu modelo de negócio.",
      "Você deve destacar as características da maior parte dos seus clientes. Qual o perfil do público foco da sua Organização?",
    ],
    name: "customerSegments",
  },
];
