export const businessModelStep = [
  {
    title: "Proposta de Valor",
    description:
      "Quais benefícios seu produto (ou serviço) entrega para seus clientes?",
    tag: "what",
    label: "O que?",
    hints: [
      "dica 1",
      "dica 1.1",
      "dica 1.2",
      "dica 1.3",
      "dica 1.4",
      "dica 1.5",
    ],
    name: "valueProposition",
  },
  {
    title: "Fonte de Receitas",
    description:
      "Por quais maneiras o cliente pagará pelos benefícios recebidos?",
    tag: "how-much",
    label: "Quanto?",
    hints: [
      "dica 2",
      "dica 2.1",
      "dica 2.2",
      "dica 2.3",
      "dica 2.4",
      "dica 2.5",
    ],
    name: "revenue",
  },
  {
    title: "Canais",
    description:
      "Caminhos pelos quais a empresa comunica e entrega valor para o cliente.",
    tag: "to-whom",
    label: "Para Quem?",
    hints: [
      "dica 3",
      "dica 3.1",
      "dica 3.2",
      "dica 3.3",
      "dica 3.4",
      "dica 3.5",
    ],
    name: "channels",
  },
  {
    title: "Relacionamento com o Cliente",
    description:
      "Estratégias que evitam que seus clientes corram para o concorrente.",
    tag: "to-whom",
    label: "Para Quem?",
    hints: [
      "dica 4",
      "dica 4.1",
      "dica 4.2",
      "dica 4.3",
      "dica 4.4",
      "dica 4.5",
    ],
    name: "customerRelationship",
  },
  {
    title: "Recursos Chave",
    description: "Quais os ativos fundamentais para fazer o negócio funcionar?",
    tag: "how",
    label: "Como?",
    hints: [
      "dica 5",
      "dica 5.1",
      "dica 5.2",
      "dica 5.3",
      "dica 5.4",
      "dica 5.5",
    ],
    name: "mainResources",
  },
  {
    title: "Parceiros Chave",
    description: "Quem são os seus principais fornecedores (terceirizados)?",
    tag: "how",
    label: "Como?",
    hints: [
      "dica 6",
      "dica 6.1",
      "dica 6.2",
      "dica 6.3",
      "dica 6.4",
      "dica 6.5",
    ],
    name: "mainPartnerships",
  },
  {
    title: "Atividades Chave",
    description: "Quais atividades mais importantes para o seu negócio?",
    tag: "how",
    label: "Como?",
    hints: ["dica 1", "dica 2", "dica 3"],
    name: "mainActivities",
  },
  {
    title: "Estrutura de Custo",
    description:
      "Quais os principais custos que têm peso no financeiro e são derivados da operacionalização do negócio?",
    tag: "how-much",
    label: "Quanto?",
    hints: ["dica 1", "dica 2", "dica 3"],
    name: "costs",
  },
  {
    title: "Segmento de Mercado",
    description: "É necessário que você defina um nicho de clientes.",
    tag: "to-whom",
    label: "Para Quem?",
    hints: ["dica 1", "dica 2", "dica 3"],
    name: "customerSegments",
  },
];
